---
# This is an example playbook to execute goss tests.
# Tests need distributed to the appropriate ansible host/groups
# prior to execution by `goss validate`.

# yamllint disable rule:line-length

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  vars:
    goss_version: v0.3.7
    goss_arch: amd64
    goss_dst: /usr/local/bin/goss
    goss_sha256sum: 357f5c7f2e7949b412bce44349cd32ab19eb3947255a8ac805f884cc2c326059
    goss_url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    goss_test_directory: /etc/goss.d
    goss_format: tap
  tasks:
    - name: Download and install Goss
      get_url:
        url: "{{ goss_url }}"
        dest: "{{ goss_dst }}"
        sha256sum: "{{ goss_sha256sum }}"
        mode: 0755
      register: download_goss
      until: download_goss is succeeded
      retries: 3

    - name: Execute Goss tests
      command: "{{ goss_dst }} -g /etc/goss.d/test_apache.yml validate --format {{ goss_format }}"
      register: test_results
      changed_when: false

    - name: Display details about the Goss results
      debug:
        msg: "{{ test_results.stdout_lines }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: test_results.rc != 0
...
